Traceback (most recent call last):
  File "perplexity.py", line 7, in <module>
    model = GPT2LMHeadModel.from_pretrained(model_id).to(device)
  File "/mnt/home/kwc/venv/my_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/mnt/home/kwc/venv/my_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/kwc/venv/my_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/mnt/home/kwc/venv/my_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/mnt/home/kwc/venv/my_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/mnt/home/kwc/venv/my_test/lib/python3.6/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
